#!/usr/bin/env python

from __future__ import print_function
from mpi4py import MPI
import socket
comm = MPI.COMM_WORLD
print("Hello! I'm rank %d from %d running in total... running on %s " % (comm.rank, comm.size,socket.gethostname()))
comm.Barrier()   # wait for everybody to synchronize _here_
