#!/bin/bash

recipe=$2
image=$1

export SINGULARITY_TMPDIR=/storage/user/$USER/sdir
export SINGULARITY_CACHEDIR=/storage/user/$USER/scache/

mkdir -p $SINGULARITY_TMPDIR
mkdir -p $SINGULARITY_CACHEDIR

sudo singularity build --tmpdir $SINGULARITY_TMPDIR $image $recipe
