#!/bin/bash

recipe=$2
image=$1

if [ -d "/data" ] ; then
    export SINGULARITY_TMPDIR=/data/shared/$USER/sbuild/
    export SINGULARITY_CACHEDIR=/data/shared/$USER/scache/
elif [ -d "/imdata" ] ; then
    export SINGULARITY_TMPDIR=/imdata/$USER/sbuild/
    export SINGULARITY_CACHEDIR=/imdata/$USER/scache/
else
    export SINGULARITY_TMPDIR=$HOME/sbuild/
    export SINGULARITY_CACHEDIR=$HOME/scache/
fi

echo $SINGULARITY_TMPDIR
mkdir -p $SINGULARITY_TMPDIR
mkdir -p $SINGULARITY_CACHEDIR

sudo singularity -dv build --tmpdir $SINGULARITY_TMPDIR --sandbox $image $recipe
